# Generated by Django 5.0.2 on 2024-03-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_add', models.CharField(max_length=20)),
                ('password1', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
    print('>>>>>>>>>>>>>>>>>>>>>>login',operations)
