# Generated by Django 5.0.2 on 2024-03-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
