# Generated by Django 5.0.2 on 2024-03-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.ImageField(default='github.png', upload_to='products/')),
                ('product_name', models.CharField(max_length=50)),
                ('product_des', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
            ],
        ),
    ]
