# Generated by Django 5.0.2 on 2024-03-31 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_tour_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
