# Generated by Django 5.0.2 on 2024-04-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_tour_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
