# Generated by Django 5.0.2 on 2024-04-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_tour_slug_alter_tour_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
