# Generated by Django 5.0.2 on 2024-04-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_tour_day_tour_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='people',
            field=models.IntegerField(null=True),
        ),
    ]
