# Generated by Django 5.0.2 on 2024-04-03 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_tour_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('Tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tour')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('Tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tour')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
