# Generated by Django 5.0.2 on 2024-04-03 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_gallary'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallary',
            name='Tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tour'),
        ),
        migrations.AlterField(
            model_name='gallary',
            name='product_img',
            field=models.ImageField(upload_to='Gallary/'),
        ),
    ]
