# Generated by Django 5.0.2 on 2024-04-03 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_program_description_alter_tag_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallary',
            old_name='product_img',
            new_name='description',
        ),
    ]
