# Generated by Django 5.0.2 on 2024-04-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_product_img_gallary_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('day', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('day_count', models.IntegerField(null=True)),
                ('subj_title', models.CharField(max_length=50)),
                ('subj_description', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
