# Generated by Django 5.0.2 on 2024-04-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_subject_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='day',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='title',
        ),
    ]
