# Generated by Django 5.0.2 on 2024-04-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_subject_day_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='description',
            new_name='main_description',
        ),
    ]
