# Generated by Django 5.0.2 on 2024-04-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='profile-images/'),
        ),
    ]
