# Generated by Django 5.0.2 on 2024-04-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_profile_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('conformemail', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('nameoncard', models.CharField(max_length=20)),
                ('cardnumber', models.CharField(max_length=12)),
                ('Expirationdate', models.DateField()),
                ('month', models.DateField()),
                ('year', models.DateField()),
                ('ccv', models.DateField()),
            ],
        ),
    ]
    print('>>>>>>>>>>operations>>>>>>>>>>',operations)
