# Generated by Django 5.0.2 on 2024-05-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
