# Generated by Django 5.0.2 on 2024-05-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_tourbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourbooking',
            name='city_booking',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='message',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='state_booking',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='street_1',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='street_2',
        ),
    ]
