# Generated by Django 5.0.2 on 2024-05-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_remove_tourbooking_city_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='ccv',
            field=models.CharField(max_length=3),
        ),
    ]
