# Generated by Django 5.0.2 on 2025-04-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_tourbooking_ccv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourbooking',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='ccv',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='expire_month',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='expire_year',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='firstname_card',
        ),
    ]
