# Generated by Django 5.2 on 2025-04-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_passwordresetotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
