# Generated by Django 5.2 on 2025-04-11 12:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='check_in',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='check_out',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='num_people',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tour'),
        ),
    ]
