# Generated by Django 5.1.6 on 2025-04-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_tourbooking_check_in_tourbooking_check_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='email_booking',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='status',
            field=models.CharField(default='success', max_length=20),
        ),
    ]
